-- create table tblConstraints(
-- id INT NOT NULL UNIQUE,
-- name VARCHAR(50) NOT NULL,
-- age INT NOT NULL CHECK (age<=18),
-- gender VARCHAR(10) NOT NULL,
-- phone VARCHAR(10) NOT NULL,
-- city VARCHAR(10) NOT NULL Default "Karachi");

-- insert into tblconstraints(
-- id, name, age, gender, phone, city)
-- values
-- (1,"Junaid",18,"Male","03133533027","Sukkur"),
-- (2,"Hassnain",17,"Male","03133533028","Karachi");
